/* Generated By:JavaCC: Do not edit this line. YousBitWarParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface YousBitWarParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 7;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 8;
  /** RegularExpression Id. */
  int STRATEGY = 9;
  /** RegularExpression Id. */
  int INT = 10;
  /** RegularExpression Id. */
  int IF = 11;
  /** RegularExpression Id. */
  int ELSEIF = 12;
  /** RegularExpression Id. */
  int ELSE = 13;
  /** RegularExpression Id. */
  int WHILE = 14;
  /** RegularExpression Id. */
  int RETURN = 15;
  /** RegularExpression Id. */
  int READ = 16;
  /** RegularExpression Id. */
  int WRITE = 17;
  /** RegularExpression Id. */
  int RANDOM = 18;
  /** RegularExpression Id. */
  int CURRENT = 19;
  /** RegularExpression Id. */
  int ENERMY = 20;
  /** RegularExpression Id. */
  int END = 21;
  /** RegularExpression Id. */
  int ASSIGN = 22;
  /** RegularExpression Id. */
  int LT = 23;
  /** RegularExpression Id. */
  int LE = 24;
  /** RegularExpression Id. */
  int EQ = 25;
  /** RegularExpression Id. */
  int GE = 26;
  /** RegularExpression Id. */
  int GT = 27;
  /** RegularExpression Id. */
  int NE = 28;
  /** RegularExpression Id. */
  int SC_OR = 29;
  /** RegularExpression Id. */
  int SC_AND = 30;
  /** RegularExpression Id. */
  int PLUS = 31;
  /** RegularExpression Id. */
  int MINUS = 32;
  /** RegularExpression Id. */
  int MULTIPLY = 33;
  /** RegularExpression Id. */
  int DIVIDE = 34;
  /** RegularExpression Id. */
  int LPAREN = 35;
  /** RegularExpression Id. */
  int RPAREN = 36;
  /** RegularExpression Id. */
  int LBRACE = 37;
  /** RegularExpression Id. */
  int RBRACE = 38;
  /** RegularExpression Id. */
  int LBRACKET = 39;
  /** RegularExpression Id. */
  int RBRACKET = 40;
  /** RegularExpression Id. */
  int SEMICOLON = 41;
  /** RegularExpression Id. */
  int COMMA = 42;
  /** RegularExpression Id. */
  int DOT = 43;
  /** RegularExpression Id. */
  int ID = 44;
  /** RegularExpression Id. */
  int CONSTANT = 45;
  /** RegularExpression Id. */
  int DIGIT = 46;
  /** RegularExpression Id. */
  int LETTER = 47;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "<FORMAL_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"Strategy\"",
    "\"int\"",
    "\"if\"",
    "\"elseif\"",
    "\"else\"",
    "\"while\"",
    "\"return\"",
    "\"read\"",
    "\"write\"",
    "\"Random\"",
    "\"Current\"",
    "\"Enermy\"",
    "\"END\"",
    "\"=\"",
    "\"<\"",
    "\"<=\"",
    "\"==\"",
    "\">=\"",
    "\">\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "<ID>",
    "<CONSTANT>",
    "<DIGIT>",
    "<LETTER>",
  };

}
