/* Generated By:JavaCC: Do not edit this line. YousBitWarJTreeTreeConstants.java Version 5.0 */
public interface YousBitWarJTreeTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTFUNCTION_STATEMENT = 1;
  public int JJTSTATEMENT_BLOCK = 2;
  public int JJTSTATEMENT_LIST = 3;
  public int JJTSTATEMENT = 4;
  public int JJTVARIABLE_DECLARATION = 5;
  public int JJTASSIGN_STATEMENT = 6;
  public int JJTIF_STATEMENT = 7;
  public int JJTWHILE_STATEMENT = 8;
  public int JJTRETURN_STATEMENT = 9;
  public int JJTEXPRESSION = 10;
  public int JJTLOGIC_EXPRESSION = 11;
  public int JJTRELATION_EXPRESSION = 12;
  public int JJTADDICTIVE_EXPRESSION = 13;
  public int JJTMULTIPLICATIVE_EXPRESSION = 14;
  public int JJTFACTOR = 15;


  public String[] jjtNodeName = {
    "program",
    "function_statement",
    "statement_block",
    "statement_list",
    "statement",
    "variable_declaration",
    "assign_statement",
    "if_statement",
    "while_statement",
    "return_statement",
    "expression",
    "logic_expression",
    "relation_expression",
    "addictive_expression",
    "multiplicative_expression",
    "factor",
  };
}
/* JavaCC - OriginalChecksum=eb743515bd2fc39781662a617723d84e (do not edit this line) */
